from __future__ import annotations

import json
from html import escape
from pathlib import Path
from typing import Any

import markdown

DEFAULT_TITLE = "Q-Forge Report"

PAGE_STYLE = """
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: linear-gradient(180deg, #f4f7fb 0%, #eef2f8 100%);
  color: #18212f;
}
.page {
  max-width: 980px;
  margin: 0 auto;
  padding: 40px 20px 64px;
}
.hero {
  background: linear-gradient(135deg, #0f172a 0%, #1d4ed8 100%);
  color: #f8fafc;
  border-radius: 20px;
  padding: 28px 32px;
  box-shadow: 0 18px 40px rgba(15, 23, 42, 0.18);
}
.hero h1 {
  margin: 0 0 8px;
  font-size: 32px;
}
.hero p {
  margin: 0;
  color: rgba(248, 250, 252, 0.82);
}
.card {
  background: #ffffff;
  border-radius: 18px;
  padding: 24px 28px;
  margin-top: 20px;
  box-shadow: 0 12px 30px rgba(15, 23, 42, 0.08);
}
.card h2 {
  margin-top: 0;
}
.markdown h1, .markdown h2, .markdown h3 {
  color: #0f172a;
}
.markdown table, .findings-table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 16px;
}
.markdown th, .markdown td, .findings-table th, .findings-table td {
  border: 1px solid #dbe4f0;
  padding: 10px 12px;
  text-align: left;
}
.markdown th, .findings-table th {
  background: #eff6ff;
}
.badge {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.02em;
}
.badge.info { background: #dbeafe; color: #1d4ed8; }
.badge.warning { background: #fef3c7; color: #92400e; }
.badge.critical { background: #fee2e2; color: #b91c1c; }
.finding {
  border-left: 4px solid #cbd5e1;
  padding: 14px 16px;
  border-radius: 14px;
  background: #f8fafc;
  margin-top: 12px;
}
.finding.warning { border-left-color: #f59e0b; }
.finding.critical { border-left-color: #ef4444; }
.meta {
  margin-top: 18px;
  color: #475569;
  font-size: 14px;
}
footer {
  margin-top: 24px;
  color: #64748b;
  font-size: 13px;
}
pre, code {
  font-family: "Cascadia Code", "SFMono-Regular", Consolas, monospace;
}
pre {
  background: #0f172a;
  color: #e2e8f0;
  padding: 14px 16px;
  border-radius: 12px;
  overflow-x: auto;
}
blockquote {
  margin: 16px 0;
  padding: 12px 16px;
  background: #f8fafc;
  border-left: 4px solid #60a5fa;
  border-radius: 0 12px 12px 0;
}
"""


def _wrap_page(title: str, subtitle: str, content_html: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{escape(title)}</title>
  <style>{PAGE_STYLE}</style>
</head>
<body>
  <div class="page">
    <section class="hero">
      <h1>{escape(title)}</h1>
      <p>{escape(subtitle)}</p>
    </section>
    {content_html}
    <footer>Generated by Q-Forge reporter core.</footer>
  </div>
</body>
</html>
"""


def render_markdown(markdown_text: str, title: str = DEFAULT_TITLE) -> str:
    body = markdown.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "nl2br"],
    )
    return _wrap_page(title, "Markdown-driven report artifact", f'<section class="card markdown">{body}</section>')


def render_markdown_file(input_path: str | Path, output_path: str | Path, title: str | None = None) -> Path:
    input_file = Path(input_path)
    output_file = Path(output_path)
    markdown_text = input_file.read_text(encoding="utf-8")
    html = render_markdown(markdown_text, title=title or input_file.stem.replace("-", " ").title())
    write_html(html, output_file)
    return output_file


def render_findings(report: dict[str, Any], title: str | None = None) -> str:
    report_title = title or str(report.get("title") or DEFAULT_TITLE)
    summary = report.get("summary") or "Structured findings rendered through the public reporter core."
    sections_html = []

    for section in report.get("sections", []):
        heading = escape(str(section.get("title") or "Section"))
        body = escape(str(section.get("body") or ""))
        bullets = section.get("bullets") or []
        bullet_html = ""
        if bullets:
            items = "".join(f"<li>{escape(str(item))}</li>" for item in bullets)
            bullet_html = f"<ul>{items}</ul>"

        table_html = ""
        table = section.get("table")
        if isinstance(table, dict):
            headers = table.get("headers") or []
            rows = table.get("rows") or []
            if headers and rows:
                head = "".join(f"<th>{escape(str(header))}</th>" for header in headers)
                body_rows = []
                for row in rows:
                    cols = "".join(f"<td>{escape(str(cell))}</td>" for cell in row)
                    body_rows.append(f"<tr>{cols}</tr>")
                table_html = f"<table class=\"findings-table\"><thead><tr>{head}</tr></thead><tbody>{''.join(body_rows)}</tbody></table>"

        sections_html.append(
            f"<section class=\"card\"><h2>{heading}</h2><p>{body}</p>{bullet_html}{table_html}</section>"
        )

    findings_html = []
    for finding in report.get("findings", []):
        severity = str(finding.get("severity") or "info").lower()
        if severity == "warn":
            severity = "warning"
        if severity not in {"info", "warning", "critical"}:
            severity = "info"
        finding_title = escape(str(finding.get("title") or "Finding"))
        detail = escape(str(finding.get("detail") or ""))
        finding_id = finding.get("id")
        label = f"{escape(str(finding_id))} · {severity}" if finding_id else severity
        findings_html.append(
            f"<article class=\"finding {severity}\">"
            f"<span class=\"badge {severity}\">{escape(label)}</span>"
            f"<h3>{finding_title}</h3>"
            f"<p>{detail}</p>"
            f"</article>"
        )

    findings_block = ""
    if findings_html:
        findings_block = f"<section class=\"card\"><h2>Findings</h2>{''.join(findings_html)}</section>"

    meta_html = ""
    if report.get("metadata"):
        pairs = []
        for key, value in sorted(report["metadata"].items()):
            pairs.append(f"<strong>{escape(str(key))}</strong>: {escape(str(value))}")
        meta_html = f"<section class=\"card\"><h2>Metadata</h2><p class=\"meta\">{'<br/>'.join(pairs)}</p></section>"

    content = "".join(
        [
            f"<section class=\"card\"><h2>Summary</h2><p>{escape(str(summary))}</p></section>",
            "".join(sections_html),
            findings_block,
            meta_html,
        ]
    )
    return _wrap_page(report_title, "Structured findings artifact", content)


def render_findings_file(input_path: str | Path, output_path: str | Path, title: str | None = None) -> Path:
    input_file = Path(input_path)
    output_file = Path(output_path)
    report = json.loads(input_file.read_text(encoding="utf-8"))
    html = render_findings(report, title=title)
    write_html(html, output_file)
    return output_file


def write_html(html_text: str, output_path: str | Path) -> Path:
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(html_text, encoding="utf-8")
    return output_file
